[package]
name = "html-macro"
version = "0.1.0"
authors = ["SebastiaanYN"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.5.19"
proc-macro2 = "1.0.28"
syn = { version = "1.0.74", features = ["extra-traits"] }
quote = "1.0.9"
